	<div id="customer-invoices">
	    <?php if( $this->getInvoices()->getSize() ): ?>
	
	    <div class="page-title">
	        <h1><?php echo $this->__('My Invoices'); ?></h1>
	    </div>
	
	    <div class="toolbar"><?php echo $this->getPagerHtml(); ?></div>
	    <table id="invoices-table" class="data-table">
	        <thead>
	            <tr>
	                <th><strong><?php echo $this->__('Invoice Number'); ?></strong></th>
	                <th><strong><?php echo $this->__('Invoice Date'); ?></strong></th>
	                <th><?php echo $this->__('Order #'); ?></th>
	                <th><?php echo $this->__('Order Date'); ?></th>
	                <th width="15%"><?php echo $this->__('Actions'); ?></th>
	            </tr>
	        </thead>
	    <?php
	        foreach( $this->getInvoices() as $invoice): ?>
	            <tr>
	                <td>
	                    <?php echo $invoice->getIncrementId(); ?>
	                </td>
	                <td>
	                    <?php echo $invoice->getCreatedAt(); ?>
	                </td>
	                <td>
	                    <a href="<?php echo $this->getUrl('sales/order/view', array('order_id' => $invoice->getOrder()->getId())); ?>">
	                        <?php echo $invoice->getOrder()->getRealOrderId(); ?>
	                    </a>
	                </td>
	                <td>
	                    <?php echo $invoice->getOrder()->getCreatedAt(); ?>
	                </td>
	                <td>
	                    <a href="<?php echo $this->getUrl('mycompany/customerInvoice/view',
	                            array('order_id' => $invoice->getOrder()->getId())); ?>">
	                        <i class="fa fa-file-pdf-o"></i>
	                        <?php echo $this->__('Create PDF'); ?>
	                    </a>
	                    &nbsp; | &nbsp;
	                    <a href="<?php echo $this->getUrl('sales/order/invoice', array('order_id' => $invoice->getOrder()->getId()))
	                    ?>">
	                        <i class="fa fa-eye"></i>
	                        <?php echo $this->__('View'); ?>
	                    </a>
	                </td>
	            </tr>
	        <?php endforeach;
	    ?>
	    </table>
	    <div class="toolbar toolbar-bottom"><?php echo $this->getPagerHtml(); ?></div>
	    <?php else: ?>
	        <p class="notice-msg"><?php echo $this->__('No invoices'); ?></p>
	    <?php endif; ?>
	</div>